dataset_root_dir: "dataset"
aerial_images_dir: "aerial_images"
pyramid_images_dir: "pyramid_images"
dem_dir: "DEM"
basemap_dir: "basemap"

rotation_angle: -1 # optional: -1, 0, 90, 180, 270 degrees, clockwise
x_resolution: 0.125 # units: meters per pixel
y_resolution: 0.23
start_frame_idx: 0 # inclusive
end_frame_idx: -1 # inclusive

clahe_clip_limit: 2.0 # CLAHE clip limit for contrast enhancement

scale_factor_crop_pyramid: 1.5 # >1 to crop more
register_ransacReprojThreshold: 7.0 # loftr image registration ransac reprojection threshold
register_min_inliers: 20 # loftr image registration minimum inliers after ransac
register_min_ratio: 0.05 # loftr image registration minimum ratio after ransac

camera_intrinsics: [ 232707, 0, 2372, 0, 232707, 1897 ]
camera_distortion: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
pnp_ransac_reprojectionError: 8.0
pnp_ransac_confidence: 0.99
pnp_ransac_iterations: 500
PnPRefineLM_min_inliers: 10 # threshold to enable LM refinement
PnPRefineLM_maxIterations: 100

ekf_sigma_p: 5 # in meters
ekf_sigma_q: 0.015 # in rad
ekf_fusion_threshold: 1200.0 # threshold if use pnp result for ekf fusion, units: meters

DEBUG: False
